#!/usr/bin/env node
require('colors');

const cp = require('child_process');
const args = require('minimist')(process.argv.slice(2));
const SFTPClient = require('ssh2-sftp-client');

const SFTP_CREDENTIALS = {
  dev: {
    host: 'clearlabsdev.sftp.wpengine.com',
    port: '2222',
    username: 'clearlabsdev-codeship-dev',
    password: '(0D3sh1pd3V'
  }
};
const FTP_IGNORE = {

};
const env = args.env;
const SFTP_SETTINGS = SFTP_CREDENTIALS[env];
const sftp = new SFTPClient();

sftp.connect(SFTP_SETTINGS)
.then(() => {
  return cp.execSync(`git log --pretty="%h" -1`).toString().split('\n').slice(-2)[0];
}).then((sinceHash) => {
  return cp.execSync(`git diff-tree --name-status --no-commit-id -r ${sinceHash}`).toString('utf-8');
}).then((data) => {
  console.log(data);
}).catch((err) => {
    console.log(err, 'catch error');
});
